initial commit

diff --git a/web_stack_debugging_2/0-iamsomeoneelse b/web_stack_debugging_2/0-iamsomeoneelse
--- a/web_stack_debugging_2/0-iamsomeoneelse
+++ b/web_stack_debugging_2/0-iamsomeoneelse
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
-#This script ensures Nginx is installed, configured to listen on port 80, and running.
-
-sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
-sudo service nginx restart
+# A script that accept argument
+if [ $# -ne 1 ]; then
+  echo "Usage: $0 <username>"
+  exit 1
+fi
+username="$1"
+if ! id -u "$username" &>/dev/null; then
+  echo "Error: User '$username' does not exist."
+  exit 1
+fi
+sudo -u "$username" whoami
+exit 0
